version: '3'
services:
  db:
    container_name: mysql_django
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django
      TZ: 'Asia/Tokyo'
  phpmyadmin:
    container_name: phpmyadmin_django
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_django
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    ports:
      - 8078:80
  web:
    build: .
    command: sh -c "./wait-for-it.sh db:3306; python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/var/www/webapp
    ports:
      - "8000:8000"
    depends_on:
      - db
