# Generated by Django 2.2.6 on 2019-12-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsukapota', '0003_news_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='contents',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
