# Generated by Django 2.2.6 on 2019-12-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsukapota', '0005_auto_20191213_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category_id',
            new_name='category',
        ),
    ]
